FROM alpine:3.11.2

ARG TEST=2.9.2

LABEL "maintainer"="Simon Baerlocher <s.baerlocher@sbaerlocher.ch>" \
    "org.opencontainers.image.authors"="Simon Baerlocher <s.baerlocher@sbaerlocher.ch>" \
    "org.opencontainers.image.licenses"="MIT" \
    "org.opencontainers.image.ref.name"="Test ${TEST}" \
    "org.opencontainers.image.title"="Test ${TEST}" \
    "org.opencontainers.image.description"="Test ${TEST}"
